version: '3'
services:
   nginx:
      image: budry/jwilder-nginx-proxy-arm
      restart: always
      ports:
        - '80:80'
      depends_on:
        - mqtt2prom
        - prom
        - graf
      volumes:
         - '/var/run/docker.sock:/tmp/docker.sock:ro'
   mqtt2prom:
     image: ghcr.io/fhemberger/mqtt_exporter
     expose:
       - '9344'
     volumes:
       - ./mqtt2prom:/usr/src/app/conf:ro
     environment:
       VIRTUAL_HOST: mqtt2prom.lvh.me
   prom:
      image: 'prom/prometheus:latest'
      restart: always
      expose:
         - '9090'
      volumes: 
        - ./prom:/etc/prometheus:ro
        - ./prom/data:/prometheus:rw
      environment:
         VIRTUAL_HOST: prom.lvh.me
   graf:
      image: 'grafana/grafana:7.1.2'
      restart: always
      expose:
         - '3000'
      volumes:
         - ./graf/data:/var/lib/grafana:rw
         - ./graf/provisioning:/etc/grafana/provisioning:ro
      environment:
         VIRTUAL_HOST: graf.lvh.me
