version: '3'
services:
   cadvisor:
      image: unibaktr/cadvisor:latest
      ports:
        - '8080:8080'
      expose:
        - '8080'
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
   nginx:
      image: budry/jwilder-nginx-proxy-arm
      restart: always
      ports:
        - '80:80'
      depends_on:
        - mqtt2prom
        - prom
        - graf
      volumes:
         - '/var/run/docker.sock:/tmp/docker.sock:ro'
   mqtt2prom:
     image: limitium/mqtt2prom
     restart: always
     expose:
       - '9344'
     volumes:
       - ./mqtt2prom/provisioning:/usr/src/app/conf:ro
   #   environment:
      #   VIRTUAL_HOST: mqtt2prom.${HOST}
   prom:
      image: 'prom/prometheus:latest'
      restart: always
      command:
         - '--config.file=/etc/prometheus/prometheus.yml'
         - '--storage.tsdb.path=/prometheus'
         - '--web.console.libraries=/etc/prometheus/console_libraries'
         - '--web.console.templates=/etc/prometheus/consoles'
         - '--storage.tsdb.retention.time=100d'
         - '--storage.tsdb.retention.size=20GB'
      expose:
         - '9090'
      volumes: 
        - ./prom/provisioning:/etc/prometheus:ro
        - ./prom/data:/prometheus:rw
      # environment:
         # VIRTUAL_HOST: prom.${HOST}
   graf:
      image: 'limitium/grafana-arm32v7-linux:latest'
      restart: always
      ports:
         - '3000:3000'
      expose:
         - '3000'
      volumes:
         - ./graf/provisioning:/etc/grafana/provisioning:ro
         - ./graf/data:/var/lib/grafana:rw
         - ./graf/grafana.ini:/etc/grafana/grafana.ini:ro
      environment:
         VIRTUAL_HOST: warden.${HOST}
         GF_SERVER_ROOT_URL: http://warden.${HOST}:3000
         GF_RENDERING_SERVER_URL: http://renderer:8081/render
         GF_RENDERING_CALLBACK_URL: http://warden:3000/
         GF_LOG_FILTERS: rendering:info
         GF_TELEGRAM_BOT_TOKEN: ${GF_TELEGRAM_BOT_TOKEN}
   renderer:
      image: adejong/grafana-image-renderer-pi:1.0.8-beta2
      restart: always
      expose: 
         - '8081'
      environment:
         ENABLE_METRICS: 'true'
         LOG_LEVEL: 'warn'
   chat_identifier:
      image: falafel/wardenbot:latest
      environment: 
         BOT_TOKEN: ${GF_TELEGRAM_BOT_TOKEN}