{
 "title": "Room-1",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "FDFC_WRDSNR01FDB6_co2", "legendFormat": "Air" }
   ]
  },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "FDFC_WRDSNR01FDB6_co2" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "FDFC_CGG10F9D_humidity", "legendFormat": "Classic" }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "FDFC_CGG10F9D_humidity" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "FDFC_CGG10F9D_temperature", "legendFormat": "Air" }
   ]
  },
  {
   "title": "Air",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "FDFC_CGG10F9D_temperature" }
   ]
  }
 ]
}