{
 "title": "Warden-2",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Humidity/Moisture",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "mars1_HHCCJCY0198fe_moisture", "legendFormat": "Classic" },
    { "expr": "mars1_HHCCJCY01932c_moisture", "legendFormat": "Cherry" },
    { "expr": "mars1_LYWSD03MMC4604_humidity", "legendFormat": "Air" }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mars1_LYWSD03MMC4604_humidity" }
   ]
  },
  {
   "title": "Moisture",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mars1_HHCCJCY0198fe_moisture", "legendFormat": "Classic" },
    { "expr": "mars1_HHCCJCY01932c_moisture", "legendFormat": "Cherry" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "mars1_HHCCJCY0198fe_temperature",
     "legendFormat": "Ground"
    },
    {
     "expr": "mars1_LYWSD03MMC4604_temperature",
     "legendFormat": "Air"
    }
   ]
  },
  {
   "title": "Air",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mars1_LYWSD03MMC4604_temperature"
    }
   ]
  },
  {
   "title": "Ground",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mars1_HHCCJCY0198fe_temperature"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mars1_LYWSD03MMC4604_battery", "legendFormat": "MMC" }
   ]
  },
  {
   "title": "Conductivity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µS/cm" } },
   "yaxes": [
    { "format": "µS/cm" }
   ],
   "targets": [
    { "expr": "mars1_HHCCJCY0198fe_fertility", "legendFormat": "Classic" },
    { "expr": "mars1_HHCCJCY01932c_fertility", "legendFormat": "Cherry" }
   ]
  },
  {
   "title": "Conductivity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mars1_HHCCJCY0198fe_fertility", "legendFormat": "Classic" },
    { "expr": "mars1_HHCCJCY01932c_fertility", "legendFormat": "Cherry" }
   ]
  },
  {
   "title": "Illuminance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mars1_HHCCJCY0198fe_illuminance",
     "legendFormat": "Classic"
    },
    {
     "expr": "mars1_HHCCJCY01932c_illuminance",
     "legendFormat": "Cherry"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µS/cm" } },
   "yaxes": [
    { "format": "µS/cm" }
   ],
   "targets": [
    { "expr": "FDFC_WRDSNR01FDB6_co2", "legendFormat": "Air" }
   ]
  },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "FDFC_WRDSNR01FDB6_co2" }
   ]
  }
 ]
}