{
 "title": "Warden",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "ground_moisture", "legendFormat": "Ground" },
    { "expr": "air_humidity", "legendFormat": "Air" },
    { "expr": "gas_humidity", "legendFormat": "Gas" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "air_humidity" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ground_moisture" }
   ]
  },
  {
   "title": "eCo2",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "gas_eco2", "legendFormat": "Gas" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "ground_temperature", "legendFormat": "Ground" },
    { "expr": "air_temperature", "legendFormat": "Air" },
    { "expr": "gas_temperature", "legendFormat": "Gas" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "air_temperature" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ground_temperature" }
   ]
  },
  {
   "title": "Illuminance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    { "expr": "ground_illuminance", "legendFormat": "Ground" }
   ]
  },
  {
   "title": "Conductivity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "ground_fertility", "legendFormat": "Ground" }
   ]
  },
  {
   "title": "eTVOC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "conppb" }
   ],
   "targets": [
    { "expr": "gas_etvoc", "legendFormat": "Gas" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ground_fertility" }
   ]
  },
  {
   "title": "Battery",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "air_battery", "legendFormat": "MMC" }
   ]
  }
 ]
}