{
 "title": "Warden",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "mars1_HHCCJCY0198fe_moisture", "legendFormat": "Ground" },
    { "expr": "mars1_LYWSD03MMC4604_humidity", "legendFormat": "Air" }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mars1_LYWSD03MMC4604_humidity" }
   ]
  },
  {
   "title": "Moisture",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mars1_HHCCJCY0198fe_moisture" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "mars1_HHCCJCY0198fe_temperature",
     "legendFormat": "Ground"
    },
    {
     "expr": "mars1_LYWSD03MMC4604_temperature",
     "legendFormat": "Air"
    }
   ]
  },
  {
   "title": "Air",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mars1_LYWSD03MMC4604_temperature"
    }
   ]
  },
  {
   "title": "Ground",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mars1_HHCCJCY0198fe_temperature"
    }
   ]
  },
  {
   "title": "Conductivity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µS/cm" } },
   "yaxes": [
    { "format": "µS/cm" }
   ],
   "targets": [
    { "expr": "mars1_HHCCJCY0198fe_fertility", "legendFormat": "Ground" }
   ]
  },
  {
   "title": "Conductivity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mars1_HHCCJCY0198fe_fertility" }
   ]
  },
  {
   "title": "Illuminance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mars1_HHCCJCY0198fe_illuminance",
     "legendFormat": "Ground"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mars1_LYWSD03MMC4604_battery", "legendFormat": "MMC" }
   ]
  }
 ]
}